<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jackson Barnett">

<title>Thesis Plots (6/15)- Final Versions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="CommitteePlots_files/libs/clipboard/clipboard.min.js"></script>
<script src="CommitteePlots_files/libs/quarto-html/quarto.js"></script>
<script src="CommitteePlots_files/libs/quarto-html/popper.min.js"></script>
<script src="CommitteePlots_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="CommitteePlots_files/libs/quarto-html/anchor.min.js"></script>
<link href="CommitteePlots_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="CommitteePlots_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="CommitteePlots_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="CommitteePlots_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="CommitteePlots_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Thesis Plots (6/15)- Final Versions</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jackson Barnett </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="all-data-anovas" class="level2">
<h2 class="anchored" data-anchor-id="all-data-anovas">All data ANOVAs</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (2 x 2) "arrange": 4 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (1-1,2-2) arrange gtable[layout]
3 3 (2-2,1-1) arrange gtable[layout]
4 4 (2-2,2-2) arrange gtable[layout]</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>kd ANOVA</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Comparison        p adj
SFT_4-Barfoot   SFT_4-Barfoot 3.005155e-02
SFT_3-Barfoot   SFT_3-Barfoot 1.513121e-03
SFT_2-Barfoot   SFT_2-Barfoot 1.618079e-03
SFT_1-Barfoot   SFT_1-Barfoot 7.662793e-04
SDY_2-Barfoot   SDY_2-Barfoot 1.919767e-04
BRI_2-Barfoot   BRI_2-Barfoot 3.076388e-05
SDY_1-Barfoot   SDY_1-Barfoot 2.170023e-05
SDY_3-Barfoot   SDY_3-Barfoot 4.352261e-05
BRI_1-Barfoot   BRI_1-Barfoot 6.716617e-07
ANNA-Barfoot     ANNA-Barfoot 8.132034e-09
BRI_2-Harrison BRI_2-Harrison 1.239678e-02
SDY_1-Harrison SDY_1-Harrison 9.348342e-03
SDY_3-Harrison SDY_3-Harrison 1.634555e-02
BRI_1-Harrison BRI_1-Harrison 4.712696e-04
ANNA-Harrison   ANNA-Harrison 7.724480e-06
SFT_3-Chick       SFT_3-Chick 3.176162e-02
SFT_2-Chick       SFT_2-Chick 3.355850e-02
SFT_1-Chick       SFT_1-Chick 1.801619e-02
SDY_2-Chick       SDY_2-Chick 5.456564e-03
BRI_2-Chick       BRI_2-Chick 1.054909e-03
SDY_1-Chick       SDY_1-Chick 7.662793e-04
SDY_3-Chick       SDY_3-Chick 1.446813e-03
BRI_1-Chick       BRI_1-Chick 2.927125e-05
ANNA-Chick         ANNA-Chick 3.990026e-07
ANNA-SFT_4         ANNA-SFT_4 7.936410e-03</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>kd ANOVA</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Site Group
Harrison Harrison   abc
Chick       Chick    ab
SFT_4       SFT_4   bcd
SFT_3       SFT_3   cde
SFT_2       SFT_2   cde
SFT_1       SFT_1   cde
SDY_2       SDY_2   cde
BRI_2       BRI_2    de
SDY_1       SDY_1    de
SDY_3       SDY_3    de
BRI_1       BRI_1    de
ANNA         ANNA     e
Barfoot   Barfoot     a</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>CDOM ANOVA</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Site Group
Harrison Harrison     a
Chick       Chick     a
SFT_4       SFT_4    bc
SFT_3       SFT_3    bc
SFT_2       SFT_2    bc
SFT_1       SFT_1    bc
SDY_2       SDY_2    bc
BRI_2       BRI_2    bc
SDY_1       SDY_1    bc
SDY_3       SDY_3    bc
BRI_1       BRI_1    bc
ANNA         ANNA     b
Barfoot   Barfoot     c</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>TSS ANOVA</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Site Group
Harrison Harrison    ab
Chick       Chick    ab
SFT_4       SFT_4     a
SFT_3       SFT_3    ab
SFT_2       SFT_2    ab
SFT_1       SFT_1    ab
SDY_2       SDY_2    ab
BRI_2       BRI_2    ab
SDY_1       SDY_1    ab
SDY_3       SDY_3    ab
BRI_1       BRI_1     b
ANNA         ANNA     b
Barfoot   Barfoot     c</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>CHLa ANOVA</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Site Group
Harrison Harrison     a
Chick       Chick     a
SFT_4       SFT_4     a
SFT_3       SFT_3     a
SFT_2       SFT_2     a
SFT_1       SFT_1     a
SDY_2       SDY_2    ab
BRI_2       BRI_2    ab
SDY_1       SDY_1     a
SDY_3       SDY_3     a
BRI_1       BRI_1     a
ANNA         ANNA     a
Barfoot   Barfoot     b</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="station-average-data" class="level2">
<h2 class="anchored" data-anchor-id="station-average-data">Station Average Data</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 5
   Site                  mean_kd mean_CDOM mean_CHLa mean_TSS
   &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 2-BRI010.78             1.10      1.75       16.4     2.77
 2 2-BRI013.12             1.36      1.99       23.1     3.64
 3 2-CHK026.94             2.56      6.45       13.5     4.52
 4 2-DYC000.19             1.63      2.06       14.2     4.5 
 5 2-MBN000.96             1.38      2.16       18.3     3.75
 6 2-SDY004.27             1.33      2.21       16.3     4.03
 7 2-SDY005.85             1.48      2.18       23.3     4.93
 8 2-SFT031.08             1.58      2.17       14.5     4.5 
 9 2-SFT033.42             1.63      1.98       11.6     5.17
10 2-SFT034.38             1.87      2.08       12.1     6.67
11 5ANTW127.14             2.80      3.18       34.5    10.8 
12 Harrison Near Dam       2.36      7.88       17.1     4.54
13 Lake Anna Dam Surface   0.825     0.560      11.1     2.08</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (3 x 1) "arrange": 3 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (2-2,1-1) arrange gtable[layout]
3 3 (3-3,1-1) arrange gtable[layout]</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (3 x 1) "arrange": 3 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (2-2,1-1) arrange gtable[layout]
3 3 (3-3,1-1) arrange gtable[layout]</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Residual Plots for Regression: kd vs TSS"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Residual Plots for Regression: Residual kd vs CDOM"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Residual Plots for Regression: Residual kd vs CHLa"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                         Predictors       AIC  Delta_AIC
1                 `TSS (mg/L)` + `CDOM a440 (corr)` -12.70936  0.0000000
2 `TSS (mg/L)` + `CDOM a440 (corr)` + `CHLa (ug/L)` -12.25530  0.4540582
3                `CDOM a440 (corr)` + `CHLa (ug/L)`  14.42792 27.1372783
4                                      `TSS (mg/L)`  16.37326 29.0826135
5                                `CDOM a440 (corr)`  16.94783 29.6571880
6                      `TSS (mg/L)` + `CHLa (ug/L)`  18.04674 30.7560956
7                                     `CHLa (ug/L)`  25.02982 37.7391749
8                                                    25.43911 38.1484699</code></pre>
</div>
</div>
<p>The best model for predicting kd (m-1) is Model 1, which includes the predictors TSS (mg/L) and CDOM a440 (corr). This model has the lowest AIC and provides the best fit to the data. Model 2, which adds CHLa (ug/L) to the combination of TSS (mg/L) and CDOM a440 (corr), has a slightly higher AIC but still performs quite well, this indicates that the addition of CHLa as a predictor adds little to no predictive power to the model. On the other hand, models with only one predictor, such as Model 4 (TSS (mg/L)), Model 5 (CDOM a440 (corr)), and Model 7 (CHLa (ug/L)), perform significantly worse, with much higher AIC values. The intercept-only model. Overall, the results suggest that TSS (mg/L) and CDOM a440 (corr) are the most important predictors for kd (m-1), and adding CHLa (ug/L) slightly reduces the model’s performance.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lake-size" class="level3">
<h3 class="anchored" data-anchor-id="lake-size">Lake Size</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = `mean_kd (m-1)` ~ mean_Lake_Size, data = mean_by_lake)

Residuals:
       1        2        3        4        5        6        7 
-0.77901  0.58470  0.74664  0.27727  0.03911 -0.62290 -0.24580 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.094e+00  2.810e-01   7.453 0.000686 ***
mean_Lake_Size -1.006e-04  5.622e-05  -1.788 0.133754    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6377 on 5 degrees of freedom
Multiple R-squared:  0.3901,    Adjusted R-squared:  0.2681 
F-statistic: 3.198 on 1 and 5 DF,  p-value: 0.1338</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="lake-anna" class="level2">
<h2 class="anchored" data-anchor-id="lake-anna">Lake Anna</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  Date   Surface_TSS Photic_TSS Bottom_TSS Surface_CHLa Photic_CHLa Surface_CDOM
  &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;
1 1/6/2…        0.53       0.44       0.66         1.92        1.73       NA    
2 2/9/2…        1.23       1.26       3.14         1.58        1.41       NA    
3 3/6/2…        0.93       1.08       3.31         1.43        2.35       NA    
4 4/21/…        1.12       1.14       3.39         2.2         2.3         0.607
5 5/19/…        2.53       2.79       2.84         4.76        5.54        0.694
6 6/16/…        1.39       1.33       1.52         4.66        3.88        0.577
# ℹ 4 more variables: Photic_CDOM &lt;dbl&gt;, Bottom_CDOM &lt;dbl&gt;, kd &lt;dbl&gt;,
#   photic_depth &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="individual-linear-regressions" class="level3">
<h3 class="anchored" data-anchor-id="individual-linear-regressions">Individual Linear Regressions</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lake Anna: Photic Zone kd vs TSS"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lake Anna: Photic Zone kd vs CDOM"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-39-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lake Anna: Photic Zone kd vs CHLa"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-39-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lake-anna-multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="lake-anna-multiple-linear-regression">Lake Anna Multiple Linear Regression</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kd ~ Photic_TSS + Photic_CDOM + Photic_CHLa, data = annadata)

Coefficients:
(Intercept)   Photic_TSS  Photic_CDOM  Photic_CHLa  
    0.69254      0.01903     -0.05681      0.01044  </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                              Predictors       AIC Delta_AIC
1                            Photic_CHLa -35.00866 0.0000000
2               Photic_TSS + Photic_CHLa -34.55346 0.4551916
3                             Photic_TSS -32.64198 2.3666706
4              Photic_CDOM + Photic_CHLa -31.70153 3.3071262
5 Photic_TSS + Photic_CDOM + Photic_CHLa -29.88434 5.1243107
6               Photic_TSS + Photic_CDOM -27.82204 7.1866139
7                                        -26.80083 8.2078294
8                            Photic_CDOM -26.06498 8.9436716</code></pre>
</div>
</div>
<p>The results of the AIC-based model comparison indicate that Photic_CHLa is the most effective predictor for kd, as the model using only Photic_CHLa (Model 1) has the lowest AIC value. This model outperforms all other combinations of predictors, suggesting that Photic_CHLa alone explains the variation in kd more effectively than any other model. The inclusion of Photic_TSS alongside Photic_CHLa (Model 2) results in only a marginal increase in AIC, indicating that adding Photic_TSS does not significantly improve the model’s predictive ability. Models using Photic_TSS or Photic_CDOM alone, such as Models 3 and 8, perform considerably worse, with higher AIC values and larger delta AIC values, highlighting that these predictors are less effective in explaining kd by themselves. Furthermore, models that combine Photic_TSS with Photic_CDOM or all three predictors (Photic_TSS, Photic_CDOM, and Photic_CHLa) result in higher AIC values, indicating that adding these predictors does not enhance model performance. Overall, the findings suggest that Photic_CHLa is the most crucial factor in predicting kd, while other variables like Photic_TSS and Photic_CDOM do not contribute meaningfully to the model.</p>
</section>
<section id="dr-bukaveckas-anna-data" class="level3">
<h3 class="anchored" data-anchor-id="dr-bukaveckas-anna-data">Dr Bukaveckas Anna Data</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kd ~ Photic_TSS + Photic_CDOM + Photic_CHLa, data = bukanna)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.13532 -0.06598 -0.01782  0.07005  0.24298 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.671553   0.083050   8.086  2.1e-07 ***
Photic_TSS   0.016815   0.046466   0.362   0.7217    
Photic_CDOM -0.045969   0.081561  -0.564   0.5800    
Photic_CHLa  0.012774   0.005523   2.313   0.0328 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1022 on 18 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3609,    Adjusted R-squared:  0.2544 
F-statistic: 3.389 on 3 and 18 DF,  p-value: 0.04074</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                              Predictors       AIC Delta_AIC
1                            Photic_CHLa -36.01859 0.0000000
2               Photic_TSS + Photic_CHLa -35.15185 0.8667399
3              Photic_CDOM + Photic_CHLa -34.16405 1.8545415
4 Photic_TSS + Photic_CDOM + Photic_CHLa -32.32352 3.6950682
5                             Photic_TSS -31.52089 4.4977009
6               Photic_TSS + Photic_CDOM -28.59936 7.4192247
7                            Photic_CDOM -26.82042 9.1981619
8                                        -26.80083 9.2177608</code></pre>
</div>
</div>
<p>Model selection based on Akaike’s Information Criterion (AIC) indicated that Photic_CHLa alone was the best predictor of light attenuation (kd), with the lowest AIC value (–36.02). Models that included CHLa with either TSS or CDOM showed slightly higher AIC values (ΔAIC &lt; 2), suggesting they are also plausible but do not substantially improve model performance. Moreover, as seen in the summary table of the multiple regression, TSS and CDOM were not statistically significant (Pvalues &gt; 0.05) of kd across this dataset. Models without CHLa—including those with only TSS, only CDOM, or both—had significantly higher AIC values (ΔAIC &gt; 4), indicating weaker support. Overall, these results suggest that CHLa is the most parsimonious and informative predictor of kd in this dataset, with little to no significant gain in explanatory power from adding other variables.</p>
</section>
</section>
<section id="polynomial-regressions" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-regressions">Polynomial Regressions</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lake Anna: Photic Zone TSS vs kd (Polynomial)"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ poly(x, degree), data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.17508 -0.07022 -0.03686  0.06762  0.20898 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.71917    0.02296  31.316  &lt; 2e-16 ***
poly(x, degree)1  0.32943    0.11250   2.928  0.00803 ** 
poly(x, degree)2 -0.12271    0.11250  -1.091  0.28777    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1125 on 21 degrees of freedom
Multiple R-squared:  0.3174,    Adjusted R-squared:  0.2524 
F-statistic: 4.882 on 2 and 21 DF,  p-value: 0.01815</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lake Anna: Photic Zone CDOM vs kd (Polynomial)"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ poly(x, degree), data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.17330 -0.08049 -0.02843  0.07158  0.21176 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.74429    0.02558  29.099   &lt;2e-16 ***
poly(x, degree)1 -0.08630    0.11721  -0.736    0.471    
poly(x, degree)2 -0.14063    0.11721  -1.200    0.246    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1172 on 18 degrees of freedom
Multiple R-squared:  0.09918,   Adjusted R-squared:  -0.0009154 
F-statistic: 0.9909 on 2 and 18 DF,  p-value: 0.3906</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-46-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lake Anna: Photic Zone CHLa vs kd (Polynomial)"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ poly(x, degree), data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.17073 -0.06312 -0.00645  0.05379  0.31927 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.71917    0.02146  33.518  &lt; 2e-16 ***
poly(x, degree)1  0.36729    0.10511   3.494  0.00216 ** 
poly(x, degree)2 -0.14988    0.10511  -1.426  0.16858    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1051 on 21 degrees of freedom
Multiple R-squared:  0.4041,    Adjusted R-squared:  0.3474 
F-statistic: 7.122 on 2 and 21 DF,  p-value: 0.004355</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-46-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="lake-anna-multiple-polynomial-regression" class="level3">
<h3 class="anchored" data-anchor-id="lake-anna-multiple-polynomial-regression">Lake Anna Multiple Polynomial Regression</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                              Predictors       AIC Delta_AIC
1                            Photic_CHLa -35.00866 0.0000000
2               Photic_TSS + Photic_CHLa -34.55346 0.4551916
3                             Photic_TSS -32.64198 2.3666706
4              Photic_CDOM + Photic_CHLa -31.70153 3.3071262
5 Photic_TSS + Photic_CDOM + Photic_CHLa -29.88434 5.1243107
6               Photic_TSS + Photic_CDOM -27.82204 7.1866139
7                                        -26.80083 8.2078294
8                            Photic_CDOM -26.06498 8.9436716</code></pre>
</div>
</div>
<p>Based on the AIC values and their corresponding Delta AIC values, the best model for explaining the response variable kd is the one that includes only the predictor Photic_CHLa, which has the lowest AIC of -35.00866 and a Delta AIC of 0. This model provides the best fit to the data without overfitting. When additional predictors such as Photic_TSS and Photic_CDOM are added, the AIC values increase, indicating that these models perform worse. Notably, the model using all three predictors (Photic_TSS + Photic_CDOM + Photic_CHLa) has an AIC of -29.88434, which is higher than the single predictor model, suggesting that the addition of extra predictors does not improve the model’s performance. This implies that some of the predictors, such as Photic_TSS and Photic_CDOM, may not provide significant explanatory power for kd. The worst-performing models are those that include combinations of Photic_TSS and Photic_CDOM, which have higher AIC values and larger Delta AIC values, further confirming that these predictors do not contribute much to explaining the variation in the response variable. In conclusion, Photic_CHLa alone appears to be the most effective predictor of kd in this dataset.</p>
</section>
</section>
<section id="secchi-depth" class="level2">
<h2 class="anchored" data-anchor-id="secchi-depth">Secchi Depth</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-50-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-50-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-50-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-50-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Not enough data for regression."</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="poc" class="level2">
<h2 class="anchored" data-anchor-id="poc">POC</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      TSS               C%       
 Min.   : 1.990   Min.   :11.80  
 1st Qu.: 3.217   1st Qu.:24.23  
 Median : 4.330   Median :28.20  
 Mean   : 5.103   Mean   :32.18  
 3rd Qu.: 5.365   3rd Qu.:39.67  
 Max.   :17.810   Max.   :69.50  </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="CommitteePlots_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>